### ISSUE TITLE
大佬，这份是不是你最新fork的？

### ISSUE THREAD

**Issue by xiebruce** [cuiyu8580/MacWeChatPlugin#1]
原作者remove的让人有点莫名其妙呀，不知道这份是不是你最新fork的？你会更新适配新版本微信吗？

**Comment by cuiyu8580** [comment]
是最新的，并且会改进之前的问题，已修复置底功能

**Comment by xiebruce** [comment]
@cuiyu8580 哦哦，感谢大佬，那就是我可以更新这个微信版本了呗，弹了好久一直没敢更新🤣
![image](https://user-images.githubusercontent.com/13575500/56786462-a43f3900-682b-11e9-9f7d-a9e344963b6a.png)
