### ISSUE TITLE
v2.3.26.17 (12699) 似乎封杀了

### ISSUE THREAD

**Issue by laris** [cuiyu8580/MacWeChatPlugin#4]
Device Type: MacBookPro13,3
System Version: Version 10.14.6 (Build 18G84)
System Language: en
WeChat Version: [2019-07-23 22:30:44] v2.3.26.17 (12699) #fb58c7dc2
WeChat Language: en
Historic Version: [2019-06-07 11:20:01] v2.3.25.21 (12481) #6df30b55c
Network Status: Reachable via WiFi
Display: *(1920x1080)/Retina

**Comment by cuiyu8580** [comment]
我的2.3.24没问题，我回头更新一下试试，有问题的话，这两天更新一下

**Comment by cuiyu8580** [comment]
已修复

**Comment by laris** [comment]
多谢

**Comment by laris** [comment]
fix in v1.0.2
close
