### ISSUE TITLE
大佬，QQPlugin没准备搞吗？或者目前有可用的吗？

### ISSUE THREAD

**Issue by xiebruce** [cuiyu8580/MacWeChatPlugin#6]
之前TKkk-iOSer大佬还有一个[QQPlugin-macOS](https://github.com/TKkk-iOSer/QQPlugin-macOS)，之前那个用着还能用，但现在QQ有更新，不知道更新后能用不？因为不知道能不能用所以不敢更新。不知道大佬有没准备搞一搞？又或者是不是已经有其他人在搞呢？

**Comment by cuiyu8580** [comment]
给你推荐一个，他要是不更新了，后面我再写一个，这个还是挺好用的
https://github.com/AsTryE/QQRedPackHelper

**Comment by cuiyu8580** [comment]
待我参考一下，今天或者明天我更新一个比较好用的，并且安装方便的出来。

**Comment by xiebruce** [comment]
@cuiyu8580 好的，大佬辛苦了，谢谢。

**Comment by cuiyu8580** [comment]
ok了，还有抢红包
https://github.com/cuiyu8580/MacQQPlugin

**Comment by xiebruce** [comment]
@cuiyu8580 感谢大佬，第一个star😄，实测QQ 6.5.5 (35572)正常！
